name: form_bloc
description: 'Easy Form State Management using BLoC pattern. Separate the Form State and Business Logic from the User Interface. Async Validation, Progress, Dynamic fields, and more.'
version: 1.0.0
homepage: 'https://github.com/GiancarloCode/form_bloc/tree/master/packages/form_bloc'
repository: 'https://github.com/GiancarloCode/form_bloc/tree/master/packages/form_bloc'
issue_tracker: 'https://github.com/GiancarloCode/form_bloc/issues'

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  meta: ^1.16.0
  bloc: ^8.1.4
  rxdart: ^0.28.0
  equatable: ^2.0.7
  collection: ^1.19.1
  uuid: ^4.5.1

dev_dependencies:
  test: ^1.25.14
  mocktail: ^1.0.4
  bloc_test: ^9.1.7
  fire_line_diff: ^1.5.5
  lints: ^5.1.1
